services:
  api:
    container_name: rob-api
    image: eduartrob/rob-api:latest
    restart: always
    # Las variables de entorno se cargar√°n desde el archivo .env
    env_file:
      - .env

  nginx:
    image: nginx:1.25-alpine
    container_name: rob-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/entrypoint.sh:/entrypoint.sh
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - api
    # Usamos una imagen de Nginx que tiene Certbot instalado
    # y ejecutamos nuestro script de entrada.
    command: /bin/sh -c "apk add --no-cache certbot openssl && chmod +x /entrypoint.sh && /entrypoint.sh"